project:
  type: website
  output-dir: docs
  render:
    - index.qmd

website:
  title: "STA 9750 Submission Material"
  description:
    Course Projects for STA 9750 at Baruch College
  site-url: "https://YashviMittal02.github.io/STA9750-2025-FALL/"
  navbar:
    background: primary
    search: false
    left:
      - href: index.qmd
        text: Home
      - href: mp3.html
        text: "Electoral College"
      - href: playlistmp.html
        text: "Playlist"
      - href: InteractiveMonteCarlo.html
        text: "Monte Carlo"

format:
  html:
    theme: sandstone
    toc: false

editor:
  mode: source
